Refactor status to use status.d dir/files #800

diff --git a/bin/maverick b/bin/maverick
--- a/bin/maverick
+++ b/bin/maverick
@@ -3,6 +3,90 @@
 # Maverick - UAV Companion Computer system
 # http://github.com/goodrobots/maverick
 
+
+### Define functions
+mavenv () {
+    if [ "x$1" == "xdev" ]; then
+        echo "Maverick Environment:   ${bgr}${white}${bold} dev ${reset}"
+    elif [ "x$1" == "xflight" ]; then
+        echo "Maverick Environment:   ${bgg}${white}${bold} flight ${reset}"
+    elif [ "x$1" == "xbootstrap" ]; then
+        echo "Maverick Environment:   ${bgb}${white}${bold} bootstrap ${reset}"
+    elif [ "x$1" == "xminimal" ]; then
+        echo "Maverick Environment:   ${bgb}${white}${bold} minimal ${reset}"
+    fi
+}
+
+status () {
+    if [ $3 -eq 0 ]; then
+        _status="${green}Running${reset}"
+    else
+        _status="${red}Stopped${reset}"
+    fi
+    if [ $4 -eq 0 ]; then
+        _atboot="${green}Enabled${reset}"
+    else
+        _atboot="${red}Disabled${reset}"
+    fi
+    echo "$1:$2:$_status | $_atboot\n"
+}
+
+startservice() {
+    srvresult=$(sudo systemctl start "$1" 2>&1)
+    if [ $? -eq 0 ]; then
+        echo " Start: ${green}Success${reset}"
+    else
+        echo " Start: ${red}Failure${reset}: $srvresult"
+    fi  
+}
+
+stopservice() {
+    srvresult=$(sudo systemctl stop "$1" 2>&1)
+    if [ $? -eq 0 ]; then
+        echo " Stop: ${green}Success${reset}"
+    else
+        echo " Stop: ${red}Failure${reset}: $srvresult"
+    fi
+}
+
+getservices() {
+    services=$(systemctl list-units -a -q --plain --no-pager |grep -e 'maverick-.*.service' |awk {'print $1'})
+    echo $services
+}
+
+# Define usage function
+usage () {
+    echo "Usage: ${green}maverick command [parameter] [--options]${reset}"
+    echo
+    echo "Commands"
+    echo " status       [service]                  Show status of all services, optional service name for status of single service"
+    echo " info                                    Display system information"
+    echo " netinfo                                 Display network information"
+    echo " self-update                             Update to latest maverick code"
+    echo " configure    [options]                  Configure system - ${bold}BEWARE this may make major changes to your existing system${reset}"
+    echo " start        [service | all]            Start Maverick service, "
+    echo " stop         [service | all]            Stop Maverick service"
+    echo " restart      [service]                  Restart Maverick service"
+    echo " enable       [service]                  Enable Maverick service at boot"
+    echo " disable      [service]                  Disable Maverick service at boot"
+    echo " log          [service]                  Display realtime log for Maverick service"
+    echo " unshallow                               Unshallow a git repo"
+    echo
+    echo "Configure Options"
+    echo " --env=[bootstrap|dev|flight|minimal]    Environment to configure: bootstrap, dev, flight or minimal"
+    echo " --dryrun                                Configure dry run - just show what would be done"
+    echo " --module=<module>                       Only make changes to module <module>"
+    echo " --debug                                 Debug output"
+    echo " --profile                               Profile performance data"
+    echo
+    echo "${bgr}${bold}WARNING: Maverick may make major changes to the system is it running on.${reset}"
+    echo "${bgr}${bold}Please do not run without understanding what it does.${reset}"
+    echo
+    exit 1
+}
+### End functions
+
+
 # If tput is available, populate colour variables
 if hash tput 2>/dev/null; then
     bgbl=$(tput setab 0)
@@ -45,37 +129,6 @@ if [[ $EUID -ne 0 && $USER != "mav" ]]; then
     echo
     exit 1
 fi
-
-# Define usage function
-usage () {
-    echo "Usage: ${green}maverick command [parameter] [--options]${reset}"
-    echo
-    echo "Commands"
-    echo " status       [service]                  Show status of all services, optional service name for status of single service"
-    echo " info                                    Display system information"
-    echo " netinfo                                 Display network information"
-    echo " self-update                             Update to latest maverick code"
-    echo " configure    [options]                  Configure system - ${bold}BEWARE this may make major changes to your existing system${reset}"
-    echo " start        [service | all]            Start Maverick service, "
-    echo " stop         [service | all]            Stop Maverick service"
-    echo " restart      [service]                  Restart Maverick service"
-    echo " enable       [service]                  Enable Maverick service at boot"
-    echo " disable      [service]                  Disable Maverick service at boot"
-    echo " log          [service]                  Display realtime log for Maverick service"
-    echo " unshallow                               Unshallow a git repo"
-    echo
-    echo "Configure Options"
-    echo " --env=[bootstrap|dev|flight|minimal]    Environment to configure: bootstrap, dev, flight or minimal"
-    echo " --dryrun                                Configure dry run - just show what would be done"
-    echo " --module=<module>                       Only make changes to module <module>"
-    echo " --debug                                 Debug output"
-    echo " --profile                               Profile performance data"
-    echo
-    echo "${bgr}${bold}WARNING: Maverick may make major changes to the system is it running on.${reset}"
-    echo "${bgr}${bold}Please do not run without understanding what it does.${reset}"
-    echo
-    exit 1
-}
 
 if [[ $# -eq 0 ]] ; then
     usage
@@ -170,18 +223,6 @@ do
             ;;
     esac
 done
-
-mavenv () {
-    if [ "x$1" == "xdev" ]; then
-        echo "Maverick Environment:   ${bgr}${white}${bold} dev ${reset}"
-    elif [ "x$1" == "xflight" ]; then
-        echo "Maverick Environment:   ${bgg}${white}${bold} flight ${reset}"
-    elif [ "x$1" == "xbootstrap" ]; then
-        echo "Maverick Environment:   ${bgb}${white}${bold} bootstrap ${reset}"
-    elif [ "x$1" == "xminimal" ]; then
-        echo "Maverick Environment:   ${bgb}${white}${bold} minimal ${reset}"
-    fi
-}
 
 # Migrate old config location - #637
 if [ -d /srv/maverick/data/config ]; then
@@ -370,19 +411,6 @@ fi
 
 # If status set, action and then exit
 if [ "$STATUS" == "true" ]; then
-    status () {
-        if [ $3 -eq 0 ]; then
-            _status="${green}Running${reset}"
-        else
-            _status="${red}Stopped${reset}"
-        fi
-        if [ $4 -eq 0 ]; then
-            _atboot="${green}Enabled${reset}"
-        else
-            _atboot="${red}Disabled${reset}"
-        fi
-        echo "$1:$2:$_status | $_atboot\n"
-    }
     if [ ! -z "$SERVICE" ]; then
         echo "Status of service: ${SERVICE}"
         systemctl -l -q --no-pager status "maverick-${SERVICE}"
@@ -405,140 +433,41 @@ if [ "$STATUS" == "true" ]; then
         fi
         echo
     else
+        # Display current environment
         if [ -e /srv/maverick/config/maverick/maverick-environment.conf ]; then
             environment=$(cat /srv/maverick/config/maverick/maverick-environment.conf)
         fi
         mavenv ${environment}
         echo
+
+        # Set output title
         statusout+="Service:Description: Status | At Boot\n"
         statusout+="------------:------------:------------------\n"
-        statusout+="${blue}Flight Controller Services${reset}\n"
-        mavfc=1
-        mavfcen=1
-        mavfcservice="<not set>"
-        for mavtype in "mavproxy" "cmavnode" "mavlink-router"; do
-            $(systemctl is-enabled "maverick-$mavtype@fc" >/dev/null 2>&1)
-            if [ $? -eq 0 ]; then
-                $(systemctl status "maverick-$mavtype@fc" >/dev/null 2>&1)
-                if [ $? -eq 0 ]; then
-                    mavfc=0
-                else
-                    mavfc=1
-                fi
-                mavfcservice="$mavtype@fc"
-                mavfcen=0
+
+        # Iterate through status directories in order
+        for statusdir in `ls -d /srv/maverick/software/maverick/bin/status.d/* | sort -V`
+        do
+            if [ -f "$statusdir/__init__" ]
+            then
+                statusout+="____________\n"
+                title=$(cat $statusdir/__init__)
+                statusout+="${blue}${title}${reset}\n"
+                # Iterate through each file in status directory, in order, and output status for each
+                for statusfile in `ls $statusdir/*.status 2>/dev/null | grep -v __init__ | sort -V`
+                do
+                    while IFS=, read -r _service _description
+                    do
+                        (systemctl status "maverick-${_service}" >/dev/null 2>&1); status=$?; (systemctl is-enabled "maverick-${_service}" >/dev/null 2>&1); statusen=$?; statusout+=$(status "${_service}" "${_description}" $status $statusen)
+                    done < $statusfile
+                done
             fi
         done
-        statusout+=$(status "${mavfcservice}" "Mavlink (FC)" $mavfc $mavfcen)
-        (systemctl status maverick-rosmaster@fc >/dev/null 2>&1); rosmfc=$?; (systemctl is-enabled maverick-rosmaster@fc >/dev/null 2>&1); rosmfcen=$?; statusout+=$(status "rosmaster@fc" "ROS (FC)" $rosmfc $rosmfcen)
-        (systemctl status maverick-mavros@fc >/dev/null 2>&1); mavrosfc=$?; (systemctl is-enabled maverick-mavros@fc >/dev/null 2>&1); mavrosfcen=$?; statusout+=$(status "mavros@fc" "Mavros (FC)" $mavrosfc $mavrosfcen)
-        (systemctl status maverick-api@fc >/dev/null 2>&1); apifc=$?; (systemctl is-enabled maverick-api@fc >/dev/null 2>&1); apifcen=$?; statusout+=$(status "api@fc" "API (FC)" $apifc $apifcen)
-        if [ "$environment" == "dev" -a -d "/srv/maverick/code/sitl" -a -f "/srv/maverick/config/dev/sitl.conf" ]; then
-            statusout+='------------:------------:------------------\n'
-            statusout+="${blue}Dev SITL Services${reset}\n"
-            (systemctl status maverick-sitl >/dev/null 2>&1); sitl=$?; (systemctl is-enabled maverick-sitl >/dev/null 2>&1); sitlen=$?; statusout+=$(status "sitl" "SITL" $sitl $sitlen)
-            mavsitl=1
-            mavsitlen=1
-            mavsitlservice="<not set>"
-            for mavtype in "mavproxy" "cmavnode" "mavlink-router"; do
-                $(systemctl is-enabled "maverick-$mavtype@sitl" >/dev/null 2>&1)
-                if [ $? -eq 0 ]; then
-                    $(systemctl status "maverick-$mavtype@sitl" >/dev/null 2>&1)
-                    if [ $? -eq 0 ]; then
-                        mavsitl=0
-                    else
-                        mavsitl=1
-                    fi
-                    mavsitlservice="$mavtype@sitl"
-                    mavsitlen=0
-                fi
-            done
-            statusout+=$(status "${mavsitlservice}" "Mavlink (SITL)" $mavsitl $mavsitlen)
-            (systemctl status maverick-rosmaster@sitl >/dev/null 2>&1); rosmsitl=$?; (systemctl is-enabled maverick-rosmaster@sitl >/dev/null 2>&1); rosmsitlen=$?; statusout+=$(status "rosmaster@sitl" "ROS (SITL)" $rosmsitl $rosmsitlen)
-            (systemctl status maverick-mavros@sitl >/dev/null 2>&1); mavrossitl=$?; (systemctl is-enabled maverick-mavros@sitl >/dev/null 2>&1); mavrossitlen=$?; statusout+=$(status "mavros@sitl" "Mavros (SITL)" $mavrossitl $mavrossitlen)
-            (systemctl status maverick-api@sitl >/dev/null 2>&1); apisitl=$?; (systemctl is-enabled maverick-api@sitl >/dev/null 2>&1); apisitlen=$?; statusout+=$(status "api@sitl" "API (SITL)" $apisitl $apisitlen)
-        fi
-        if [ "$environment" == "dev" -a -d "/srv/maverick/code/px4" -a -f "/srv/maverick/config/dev/px4sitl.conf" ]; then
-            statusout+='------------:------------:------------------\n'
-            statusout+="${blue}Dev PX4 SITL Services${reset}\n"
-            (systemctl status maverick-px4sitl >/dev/null 2>&1); sitl=$?; (systemctl is-enabled maverick-px4sitl >/dev/null 2>&1); sitlen=$?; statusout+=$(status "px4sitl" "PX4 SITL" $sitl $sitlen)
-            mavsitl=1
-            mavsitlen=1
-            mavsitlservice="<not set>"
-            for mavtype in "mavproxy" "cmavnode" "mavlink-router"; do
-                $(systemctl is-enabled "maverick-$mavtype@px4sitl" >/dev/null 2>&1)
-                if [ $? -eq 0 ]; then
-                    $(systemctl status "maverick-$mavtype@px4sitl" >/dev/null 2>&1)
-                    if [ $? -eq 0 ]; then
-                        mavsitl=0
-                    else
-                        mavsitl=1
-                    fi
-                    mavsitlservice="$mavtype@px4sitl"
-                    mavsitlen=0
-                fi
-            done
-            statusout+=$(status "${mavsitlservice}" "Mavlink (PX4 SITL)" $mavsitl $mavsitlen)
-            (systemctl status maverick-rosmaster@px4sitl >/dev/null 2>&1); rosmsitl=$?; (systemctl is-enabled maverick-rosmaster@px4sitl >/dev/null 2>&1); rosmsitlen=$?; statusout+=$(status "rosmaster@px4sitl" "ROS (PX4 SITL)" $rosmsitl $rosmsitlen)
-            (systemctl status maverick-mavros@px4sitl >/dev/null 2>&1); mavrossitl=$?; (systemctl is-enabled maverick-mavros@px4sitl >/dev/null 2>&1); mavrossitlen=$?; statusout+=$(status "mavros@px4sitl" "Mavros (PX4 SITL)" $mavrossitl $mavrossitlen)
-            (systemctl status maverick-api@px4sitl >/dev/null 2>&1); apisitl=$?; (systemctl is-enabled maverick-api@px4sitl >/dev/null 2>&1); apisitlen=$?; statusout+=$(status "api@px4sitl" "API (PX4 SITL)" $apisitl $apisitlen)
-        fi
-        statusout+='------------:------------:------------------\n'
-        statusout+="${blue}Web Services${reset}\n"
-        (systemctl status maverick-webdev >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-webdev >/dev/null 2>&1); statusen=$?; statusout+=$(status "webdev" "Maverick Web Devserver" $status $statusen)
-        (systemctl status maverick-nginx >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-nginx >/dev/null 2>&1); statusen=$?; statusout+=$(status "nginx" "Webserver" $status $statusen)
-        (systemctl status maverick-cloud9 >/dev/null 2>&1); c9=$?; (systemctl is-enabled maverick-cloud9 >/dev/null 2>&1); c9en=$?; statusout+=$(status "cloud9" "Cloud9 IDE" $c9 $c9en)
-        (systemctl status maverick-mavcesium >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-mavcesium >/dev/null 2>&1); statusen=$?; statusout+=$(status "mavcesium" "MavCesium" $status $statusen)
-        (systemctl status maverick-webvision >/dev/null 2>&1); vis=$?; (systemctl is-enabled maverick-webvision >/dev/null 2>&1); visen=$?; statusout+=$(status "webvision" "Web Vision" $vis $visen)
-        statusout+='------------:------------:------------------\n'
-        statusout+="${blue}Analysis Services${reset}\n"
-        (systemctl status maverick-grafana >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-grafana >/dev/null 2>&1); statusen=$?; statusout+=$(status "grafana" "Analysis Dashboard" $status $statusen)
-        (systemctl status maverick-mavlogd >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-mavlogd >/dev/null 2>&1); statusen=$?; statusout+=$(status "mavlogd" "Log Import Daemon" $status $statusen)
-        (systemctl status maverick-influxd >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-influxd >/dev/null 2>&1); statusen=$?; statusout+=$(status "influxd" "Time Data DB" $status $statusen)
-        (systemctl status maverick-collectd >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-collectd >/dev/null 2>&1); statusen=$?; statusout+=$(status "collectd" "System Metrics" $status $statusen)
-        (systemctl status maverick-uploader >/dev/null 2>&1); status=$?; (systemctl is-enabled maverick-uploader >/dev/null 2>&1); statusen=$?; statusout+=$(status "uploader" "Log Uploader Daemon" $status $statusen)
-        statusout+='------------:------------:------------------\n'
-        statusout+="${blue}Network Services${reset}\n"
-        (systemctl status maverick-wifibc_tx >/dev/null 2>&1); wifibc=$?; (systemctl is-enabled maverick-wifibc_tx >/dev/null 2>&1); wifibcen=$?; statusout+=$(status "wifibc_tx" "WifiBC TX" $wifibc $wifibcen)
-        (systemctl status maverick-wifibc_rx >/dev/null 2>&1); wifibc=$?; (systemctl is-enabled maverick-wifibc_rx >/dev/null 2>&1); wifibcen=$?; statusout+=$(status "wifibc_rx" "WifiBC RX" $wifibc $wifibcen)
-        statusout+='------------:------------:------------------\n'
-        statusout+="${blue}Vision Services${reset}\n"
-        (systemctl status maverick-visiond >/dev/null 2>&1); vis=$?; (systemctl is-enabled maverick-visiond >/dev/null 2>&1); visen=$?; statusout+=$(status "visiond" "Vision Daemon" $vis $visen)
-        (systemctl status maverick-csd >/dev/null 2>&1); csd=$?; (systemctl is-enabled maverick-csd >/dev/null 2>&1); csden=$?; statusout+=$(status "csd" "Camera Streaming Daemon" $csd $csden)
-        (systemctl status maverick-vision_landing >/dev/null 2>&1); visland=$?; (systemctl is-enabled maverick-vision_landing >/dev/null 2>&1); vislanden=$?; statusout+=$(status "vision_landing" "Vision Landing" $visland $vislanden)
-        (systemctl status maverick-vision_seek >/dev/null 2>&1); seek=$?; (systemctl is-enabled maverick-vision_seek >/dev/null 2>&1); seeken=$?; statusout+=$(status "vision_seek" "Seek Thermal Vision" $seek $seeken)
-        (systemctl status maverick-flirone >/dev/null 2>&1); flir=$?; (systemctl is-enabled maverick-flirone >/dev/null 2>&1); fliren=$?; statusout+=$(status "flirone" "Flir One Vision" $flir $fliren)
-        (systemctl status maverick-coav >/dev/null 2>&1); coav=$?; (systemctl is-enabled maverick-coav >/dev/null 2>&1); coaven=$?; statusout+=$(status "coav" "Collision Avoidance" $coav $coaven)
-    
+
         echo -e $statusout | column -c 3 -s : -t
         echo
     fi
-    
     exit 0
 fi
-
-startservice() {
-    srvresult=$(sudo systemctl start "$1" 2>&1)
-    if [ $? -eq 0 ]; then
-        echo " Start: ${green}Success${reset}"
-    else
-        echo " Start: ${red}Failure${reset}: $srvresult"
-    fi  
-}
-
-stopservice() {
-    srvresult=$(sudo systemctl stop "$1" 2>&1)
-    if [ $? -eq 0 ]; then
-        echo " Stop: ${green}Success${reset}"
-    else
-        echo " Stop: ${red}Failure${reset}: $srvresult"
-    fi
-}
-
-getservices() {
-    services=$(systemctl list-units -a -q --plain --no-pager |grep -e 'maverick-.*.service' |awk {'print $1'})
-    echo $services
-}
 
 # If start requested, action and then exit
 if [ "$START" == "true" ]; then
