Fixes #142: Add python detect/install to maverick

diff --git a/bin/maverick b/bin/maverick
--- a/bin/maverick
+++ b/bin/maverick
@@ -210,6 +210,28 @@ if ! $puppetinstalled; then
     exit 1
 fi
 
+# Check that python is installed
+if ! hash python 2>/dev/null; then
+    echo 'Python not installed, attempting to install..'
+    if hash apt-get 2>/dev/null; then
+        if [ $EUID -eq 0 ]; then
+            DEBIAN_FRONTEND=noninteractive apt-get -y install python >/dev/null 2>&1
+        elif [ $USER == "mav" ]; then
+            sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python >/dev/null 2>&1
+        fi
+        if hash python; then
+            pythoninstalled=true
+        fi
+    fi
+else
+    pythoninstalled=true
+fi
+if ! $pythoninstalled; then
+    echo 'Error: Python not installed and could not be installed'
+    echo
+    exit 1
+fi
+
 # If git is installed at this point, then force git to ignore any changes to localconf.json
 #  in the current directory, which might contain sensitive information
 if hash git 2>/dev/null; then
